#!/usr/bin/env bash
# envoy-bootstrap.sh — one-line Olympus Envoy setup for a REMOTE node.
#
# Served by the Hall at GET /api/enroll/<token>/install.sh with the three
# {{PLACEHOLDER}} values baked in. The operator runs:
#
#   curl -fsSL https://<hall>/api/enroll/<token>/install.sh | bash
#
# What it does (idempotent — re-running upgrades the binary and restarts):
#   1. sanity-checks the platform (Linux x86_64, curl, systemd user session)
#   2. downloads the olympus-envoy binary from the Hall (enroll-token-gated)
#   3. generates/loads the envoy's iroh identity and prints its node id
#   4. registers the node id with the Hall (appended to the allowlist)
#   5. installs a systemd user unit and starts the envoy (iroh transport)
#   6. polls the Hall until the envoy is registered and online
#
# Security: the embedded token is a short-lived (15 min), single-registration
# enrollment capability — NOT an API token. It cannot read or drive sessions.
set -euo pipefail

HALL_URL="{{HALL_URL}}"
ENROLL_TOKEN="{{ENROLL_TOKEN}}"
HALL_IROH_ID="{{HALL_IROH_ID}}"

OLYMPUS_HOME="${OLYMPUS_HOME:-$HOME/.olympus}"
NODE_ID="${NODE_ID:-$(hostname -s 2>/dev/null || hostname)}"
BIN_DIR="$OLYMPUS_HOME/bin"
UNIT_DIR="$HOME/.config/systemd/user"

log()  { printf '\033[1;32m▸\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m⚠\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# ── 1. Platform sanity ──────────────────────────────────────────────────
[[ "$(uname -s)" == "Linux" ]] || die "unsupported OS: $(uname -s) (Linux only)"
[[ "$(uname -m)" == "x86_64" ]] || die "unsupported arch: $(uname -m) (x86_64 only)"
command -v curl >/dev/null || die "curl is required"
command -v systemctl >/dev/null || die "systemd is required"
systemctl --user show-environment >/dev/null 2>&1 \
    || die "no systemd user session — log in as a regular user (not via 'sudo su')"

if command -v loginctl >/dev/null 2>&1; then
    if ! loginctl show-user "$(whoami)" 2>/dev/null | grep -q "Linger=yes"; then
        warn "linger is OFF — the envoy will stop when you log out."
        warn "  enable with: sudo loginctl enable-linger $(whoami)"
    fi
fi

log "Enrolling node '$NODE_ID' with Hall: $HALL_URL"

# ── 2. Download the envoy binary ────────────────────────────────────────
mkdir -p "$BIN_DIR"
STAMP="$(date +%s)"
TARGET="$BIN_DIR/olympus-envoy-enroll-$STAMP"
log "Downloading olympus-envoy binary…"
curl -fsSL "$HALL_URL/api/enroll/$ENROLL_TOKEN/binary" -o "$TARGET" \
    || die "binary download failed (token expired? Hall unreachable?)"
chmod +x "$TARGET"
ln -sfn "$(basename "$TARGET")" "$BIN_DIR/olympus-envoy"
log "  $BIN_DIR/olympus-envoy → $(basename "$TARGET")"

# ── 3. Generate/load the iroh identity ──────────────────────────────────
IROH_ID="$("$BIN_DIR/olympus-envoy" --print-node-id --node-id "$NODE_ID")" \
    || die "could not obtain the envoy's iroh node id"
[[ -n "$IROH_ID" ]] || die "envoy printed an empty iroh node id"
log "Envoy iroh node id: $IROH_ID"

# ── 4. Register with the Hall (allowlist append) ────────────────────────
log "Registering with Hall…"
HTTP_CODE="$(curl -fsS -o /tmp/olympus-enroll-resp.json -w '%{http_code}' \
    -X POST -H 'content-type: application/json' \
    -d "{\"irohNodeId\":\"$IROH_ID\",\"nodeId\":\"$NODE_ID\"}" \
    "$HALL_URL/api/enroll/$ENROLL_TOKEN")" \
    || die "registration request failed: $(cat /tmp/olympus-enroll-resp.json 2>/dev/null)"
[[ "$HTTP_CODE" == "200" ]] || die "registration rejected (HTTP $HTTP_CODE): $(cat /tmp/olympus-enroll-resp.json)"
log "  allowlisted."

# ── 5. Install + start the systemd user unit ────────────────────────────
mkdir -p "$UNIT_DIR"
cat > "$UNIT_DIR/olympus-envoy@.service" <<'UNIT'
[Unit]
Description=Olympus Envoy %i — agent runtime holder (ACP children)
After=network-online.target

[Service]
Type=simple
Environment="PATH=%h/.local/bin:%h/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ExecStart=%h/.olympus/bin/olympus-envoy
Restart=on-failure
RestartSec=5
KillMode=mixed
KillSignal=SIGTERM
TimeoutStopSec=10

[Install]
WantedBy=default.target
UNIT

INSTANCE="1"
DROPIN_DIR="$UNIT_DIR/olympus-envoy@.service.d"
mkdir -p "$DROPIN_DIR"
cat > "$DROPIN_DIR/instance-$INSTANCE.conf" <<DROPIN
# Auto-generated by envoy-bootstrap.sh. Re-run the enroll one-liner to update.
[Service]
ExecStart=
ExecStart=$BIN_DIR/olympus-envoy --hall iroh:$HALL_IROH_ID --node-id $NODE_ID
Environment="OLYMPUS_NODE_ID=$NODE_ID"
Environment="OLYMPUS_HOME=$OLYMPUS_HOME"
DROPIN

systemctl --user daemon-reload
systemctl --user enable "olympus-envoy@$INSTANCE.service" >/dev/null 2>&1 || true
if systemctl --user is-active --quiet "olympus-envoy@$INSTANCE.service"; then
    log "Envoy already running — restarting to pick up the new binary/config"
    systemctl --user restart "olympus-envoy@$INSTANCE.service"
else
    systemctl --user start "olympus-envoy@$INSTANCE.service"
fi

# ── 6. Verify registration ──────────────────────────────────────────────
log "Waiting for the envoy to connect (up to 60s)…"
for i in $(seq 1 60); do
    STATUS="$(curl -fsS "$HALL_URL/api/enroll/$ENROLL_TOKEN/status" 2>/dev/null || true)"
    if printf '%s' "$STATUS" | grep -q '"online":true'; then
        log "✓ Node '$NODE_ID' is ONLINE in the fleet."
        log "  It will appear in the Fleet view momentarily."
        exit 0
    fi
    sleep 1
done

warn "envoy did not come online within 60s."
warn "Diagnose with:"
warn "  systemctl --user status olympus-envoy@$INSTANCE"
warn "  journalctl --user -u olympus-envoy@$INSTANCE -n 50 --no-pager"
exit 4
