#!/usr/bin/env bash
# orbit-bootstrap.sh — one-line Stellarc Orbit setup for a REMOTE node.
#
# Served by the Axis at GET /api/enroll/<token>/install.sh with the three
# {{PLACEHOLDER}} values baked in. The operator runs:
#
#   curl -fsSL https://<axis>/api/enroll/<token>/install.sh | bash
#
# What it does (idempotent — re-running upgrades the binary and restarts):
#   1. sanity-checks the platform (Linux x86_64, curl, systemd user session)
#   2. downloads the stellarc-orbit binary from the Axis (enroll-token-gated)
#   3. generates/loads the orbit's iroh identity and prints its node id
#   4. registers the node id with the Axis (appended to the allowlist)
#   5. installs a systemd user unit and starts the orbit (iroh transport)
#   6. polls the Axis until the orbit is registered and online
#
# Security: the embedded token is a short-lived (15 min), single-registration
# enrollment capability — NOT an API token. It cannot read or drive sessions.
set -euo pipefail

AXIS_URL="{{AXIS_URL}}"
ENROLL_TOKEN="{{ENROLL_TOKEN}}"
AXIS_IROH_ID="{{AXIS_IROH_ID}}"

STELLARC_HOME="${STELLARC_HOME:-$HOME/.stellarc}"
NODE_ID="${NODE_ID:-$(hostname -s 2>/dev/null || hostname)}"
BIN_DIR="$STELLARC_HOME/bin"
UNIT_DIR="$HOME/.config/systemd/user"

log()  { printf '\033[1;32m▸\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m⚠\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# ── 1. Platform sanity ──────────────────────────────────────────────────
[[ "$(uname -s)" == "Linux" ]] || die "unsupported OS: $(uname -s) (Linux only)"
[[ "$(uname -m)" == "x86_64" ]] || die "unsupported arch: $(uname -m) (x86_64 only)"
command -v curl >/dev/null || die "curl is required"
command -v systemctl >/dev/null || die "systemd is required"
systemctl --user show-environment >/dev/null 2>&1 \
    || die "no systemd user session — log in as a regular user (not via 'sudo su')"

if command -v loginctl >/dev/null 2>&1; then
    if ! loginctl show-user "$(whoami)" 2>/dev/null | grep -q "Linger=yes"; then
        warn "linger is OFF — the orbit will stop when you log out."
        warn "  enable with: sudo loginctl enable-linger $(whoami)"
    fi
fi

log "Enrolling node '$NODE_ID' with Axis: $AXIS_URL"

# ── 2. Download the orbit binary ────────────────────────────────────────
install -d -m 0700 "$STELLARC_HOME" "$BIN_DIR"
STAMP="$(date +%s)"
TARGET="$BIN_DIR/stellarc-orbit-enroll-$STAMP"
log "Downloading stellarc-orbit binary…"
curl -fsSL "$AXIS_URL/api/enroll/$ENROLL_TOKEN/binary" -o "$TARGET" \
    || die "binary download failed (token expired? Axis unreachable?)"
chmod +x "$TARGET"
ln -sfn "$(basename "$TARGET")" "$BIN_DIR/stellarc-orbit"
log "  $BIN_DIR/stellarc-orbit → $(basename "$TARGET")"

# ── 3. Generate/load the iroh identity ──────────────────────────────────
IROH_ID="$("$BIN_DIR/stellarc-orbit" --print-node-id --node-id "$NODE_ID")" \
    || die "could not obtain the orbit's iroh node id"
[[ -n "$IROH_ID" ]] || die "orbit printed an empty iroh node id"
log "Orbit iroh node id: $IROH_ID"

# ── 4. Register with the Axis (allowlist append) ────────────────────────
log "Registering with Axis…"
HTTP_CODE="$(curl -fsS -o /tmp/stellarc-enroll-resp.json -w '%{http_code}' \
    -X POST -H 'content-type: application/json' \
    -d "{\"irohNodeId\":\"$IROH_ID\",\"nodeId\":\"$NODE_ID\"}" \
    "$AXIS_URL/api/enroll/$ENROLL_TOKEN")" \
    || die "registration request failed: $(cat /tmp/stellarc-enroll-resp.json 2>/dev/null)"
[[ "$HTTP_CODE" == "200" ]] || die "registration rejected (HTTP $HTTP_CODE): $(cat /tmp/stellarc-enroll-resp.json)"
log "  allowlisted."

# ── 5. Install + start the systemd user unit ────────────────────────────
mkdir -p "$UNIT_DIR"
cat > "$UNIT_DIR/stellarc-orbit@.service" <<'UNIT'
[Unit]
Description=Stellarc Orbit %i — agent runtime holder (ACP children)
After=network-online.target

[Service]
Type=simple
Environment="PATH=%h/.local/bin:%h/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ExecStart=%h/.stellarc/bin/stellarc-orbit
Restart=on-failure
RestartSec=5
KillMode=mixed
KillSignal=SIGTERM
TimeoutStopSec=10
UMask=0077

[Install]
WantedBy=default.target
UNIT

INSTANCE="1"
DROPIN_DIR="$UNIT_DIR/stellarc-orbit@.service.d"
mkdir -p "$DROPIN_DIR"
cat > "$DROPIN_DIR/instance-$INSTANCE.conf" <<DROPIN
# Auto-generated by orbit-bootstrap.sh. Re-run the enroll one-liner to update.
[Service]
ExecStart=
ExecStart=$BIN_DIR/stellarc-orbit --axis iroh:$AXIS_IROH_ID --node-id $NODE_ID
Environment="STELLARC_NODE_ID=$NODE_ID"
Environment="STELLARC_HOME=$STELLARC_HOME"
DROPIN

systemctl --user daemon-reload
systemctl --user enable "stellarc-orbit@$INSTANCE.service" >/dev/null 2>&1 || true
if systemctl --user is-active --quiet "stellarc-orbit@$INSTANCE.service"; then
    log "Orbit already running — restarting to pick up the new binary/config"
    systemctl --user restart "stellarc-orbit@$INSTANCE.service"
else
    systemctl --user start "stellarc-orbit@$INSTANCE.service"
fi

# ── 6. Verify registration ──────────────────────────────────────────────
log "Waiting for the orbit to connect (up to 60s)…"
for i in $(seq 1 60); do
    STATUS="$(curl -fsS "$AXIS_URL/api/enroll/$ENROLL_TOKEN/status" 2>/dev/null || true)"
    if printf '%s' "$STATUS" | grep -q '"online":true'; then
        log "✓ Node '$NODE_ID' is ONLINE in the fleet."
        log "  It will appear in the Fleet view momentarily."
        exit 0
    fi
    sleep 1
done

warn "orbit did not come online within 60s."
warn "Diagnose with:"
warn "  systemctl --user status stellarc-orbit@$INSTANCE"
warn "  journalctl --user -u stellarc-orbit@$INSTANCE -n 50 --no-pager"
exit 4
