export const tierOrder = ["foundation", "atom", "molecule", "organism"] as const;

export type RegistryTier = (typeof tierOrder)[number];
export type RegistryStatus = "available" | "covered" | "native/third-party" | "application-only";
export type ImplementationChoice = "registry" | "native" | "existing";

export interface RegistryEntry {
  slug: string;
  name: string;
  tier: RegistryTier;
  source: "base-nova";
  status: RegistryStatus;
  implementationChoice: ImplementationChoice;
  configuration: readonly string[];
  playgroundKey: string | null;
}

export const registry: readonly RegistryEntry[] = [
  {
    slug: "direction",
    name: "Direction",
    tier: "foundation",
    source: "base-nova",
    status: "available",
    implementationChoice: "registry",
    configuration: ["LTR/RTL", "nested override"],
    playgroundKey: null,
  },
  {
    slug: "aspect-ratio",
    name: "Aspect Ratio",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "native",
    configuration: ["ratio presets", "responsive width"],
    playgroundKey: "layout-atoms",
  },
  {
    slug: "badge",
    name: "Badge",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["variant", "label", "icon", "removable"],
    playgroundKey: "badge",
  },
  {
    slug: "button",
    name: "Button",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["variant", "size", "disabled", "loading", "icon-only", "render target"],
    playgroundKey: "buttons",
  },
  {
    slug: "checkbox",
    name: "Checkbox",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["checked", "unchecked", "indeterminate", "disabled", "invalid"],
    playgroundKey: "toggles",
  },
  {
    slug: "input",
    name: "Input",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "native",
    configuration: ["type", "value", "placeholder", "disabled", "readonly", "invalid"],
    playgroundKey: "inputs",
  },
  {
    slug: "textarea",
    name: "Textarea",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "native",
    configuration: ["rows", "resize", "disabled", "readonly", "invalid"],
    playgroundKey: "inputs",
  },
  {
    slug: "label",
    name: "Label",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "native",
    configuration: ["required", "optional", "disabled", "invalid"],
    playgroundKey: "inputs",
  },
  {
    slug: "native-select",
    name: "Native Select",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "native",
    configuration: ["options", "optgroup", "disabled", "invalid", "size"],
    playgroundKey: "native-select",
  },
  {
    slug: "progress",
    name: "Progress",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["value", "max", "indeterminate", "complete"],
    playgroundKey: "progress",
  },
  {
    slug: "separator",
    name: "Separator",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "native",
    configuration: ["horizontal", "vertical", "decorative/semantic"],
    playgroundKey: "layout-atoms",
  },
  {
    slug: "skeleton",
    name: "Skeleton",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["dimensions", "shape", "grouped loading layout"],
    playgroundKey: "skeleton",
  },
  {
    slug: "spinner",
    name: "Spinner",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["size", "label", "inline/block", "reduced motion"],
    playgroundKey: "spinner",
  },
  {
    slug: "switch",
    name: "Switch",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["checked", "disabled", "required", "label position"],
    playgroundKey: "toggles",
  },
  {
    slug: "toggle",
    name: "Toggle",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["pressed", "disabled", "variant", "size", "icon-only"],
    playgroundKey: "extended-atoms",
  },
  {
    slug: "toggle-group",
    name: "Toggle Group",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["single/multiple", "orientation", "disabled", "roving focus"],
    playgroundKey: "extended-atoms",
  },
  {
    slug: "kbd",
    name: "Kbd",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["key combinations", "platform glyphs", "sequences"],
    playgroundKey: "kbd",
  },
  {
    slug: "marker",
    name: "Marker",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["tone", "label", "icon", "compact mode"],
    playgroundKey: "layout-atoms",
  },
  {
    slug: "avatar",
    name: "Avatar",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["image", "fallback", "delayed load", "size", "status"],
    playgroundKey: "avatar",
  },
  {
    slug: "radio-group",
    name: "Radio Group",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["value", "orientation", "disabled item/group", "invalid"],
    playgroundKey: "radio-group",
  },
  {
    slug: "slider",
    name: "Slider",
    tier: "atom",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["min/max/step", "single/range", "vertical", "disabled"],
    playgroundKey: "slider",
  },
  {
    slug: "input-otp",
    name: "Input OTP",
    tier: "atom",
    source: "base-nova",
    status: "available",
    implementationChoice: "registry",
    configuration: ["length", "pattern", "disabled", "invalid", "paste"],
    playgroundKey: null,
  },
  {
    slug: "table",
    name: "Table",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["density", "sorting affordance", "selection", "empty/loading", "overflow"],
    playgroundKey: "content-molecules",
  },
  {
    slug: "accordion",
    name: "Accordion",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["single/multiple", "collapsible", "disabled item"],
    playgroundKey: "disclosure",
  },
  {
    slug: "alert",
    name: "Alert",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["default/destructive/success", "icon", "title", "action"],
    playgroundKey: "content-molecules",
  },
  {
    slug: "alert-dialog",
    name: "Alert Dialog",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["open", "destructive/non-destructive", "pending", "focus return"],
    playgroundKey: "extended-overlays",
  },
  {
    slug: "breadcrumb",
    name: "Breadcrumb",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["current page", "collapse", "custom separator"],
    playgroundKey: "navigation",
  },
  {
    slug: "button-group",
    name: "Button Group",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["orientation", "attached/split", "disabled", "mixed controls"],
    playgroundKey: "extended-atoms",
  },
  {
    slug: "card",
    name: "Card",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["header/media/content/footer", "selected", "interactive"],
    playgroundKey: "card",
  },
  {
    slug: "collapsible",
    name: "Collapsible",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["open", "disabled", "controlled", "animated"],
    playgroundKey: "disclosure",
  },
  {
    slug: "combobox",
    name: "Combobox",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["query", "empty/loading", "disabled", "clearable", "single/multi"],
    playgroundKey: "select",
  },
  {
    slug: "context-menu",
    name: "Context Menu",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["checkbox/radio/submenu", "disabled", "destructive"],
    playgroundKey: "overlays",
  },
  {
    slug: "dialog",
    name: "Dialog",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["controlled open", "size", "scroll", "pending", "dismissibility"],
    playgroundKey: "overlays",
  },
  {
    slug: "drawer",
    name: "Drawer",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["side", "snap points", "modal/non-modal", "dismissible"],
    playgroundKey: "overlays",
  },
  {
    slug: "dropdown-menu",
    name: "Dropdown Menu",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["groups", "checks", "radios", "submenu", "disabled/destructive"],
    playgroundKey: "overlays",
  },
  {
    slug: "empty",
    name: "Empty",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["icon", "title", "description", "primary/secondary action"],
    playgroundKey: "content-molecules",
  },
  {
    slug: "field",
    name: "Field",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["required", "invalid", "disabled", "horizontal", "help/error"],
    playgroundKey: "structured-fields",
  },
  {
    slug: "hover-card",
    name: "Hover Card",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["open delay", "side/alignment", "rich preview", "touch fallback"],
    playgroundKey: "overlays",
  },
  {
    slug: "input-group",
    name: "Input Group",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["prefix", "suffix", "action", "textarea", "focus/invalid"],
    playgroundKey: "structured-fields",
  },
  {
    slug: "item",
    name: "Item",
    tier: "molecule",
    source: "base-nova",
    status: "native/third-party",
    implementationChoice: "native",
    configuration: ["size", "media/icon", "selected", "disabled", "actions"],
    playgroundKey: null,
  },
  {
    slug: "pagination",
    name: "Pagination",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["first/last", "current", "disabled", "compact", "unknown total"],
    playgroundKey: "navigation",
  },
  {
    slug: "popover",
    name: "Popover",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["side", "align", "modal/non-modal", "collision", "controlled open"],
    playgroundKey: "overlays",
  },
  {
    slug: "scroll-area",
    name: "Scroll Area",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "native",
    configuration: ["orientation", "fixed size", "overflow", "always/hover scrollbar"],
    playgroundKey: "layout-atoms",
  },
  {
    slug: "select",
    name: "Select",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["type", "disabled", "scrolling; add groups", "clear", "invalid"],
    playgroundKey: "select",
  },
  {
    slug: "sheet",
    name: "Sheet",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["side", "width", "modal", "scroll", "dismissibility"],
    playgroundKey: "extended-overlays",
  },
  {
    slug: "tabs",
    name: "Tabs",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["orientation", "activation mode", "disabled tab", "overflow"],
    playgroundKey: "tabs",
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    tier: "molecule",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["delay", "side", "disabled trigger", "keyboard/touch behavior"],
    playgroundKey: "overlays",
  },
  {
    slug: "toast",
    name: "Toast",
    tier: "molecule",
    source: "base-nova",
    status: "available",
    implementationChoice: "registry",
    configuration: ["tone", "duration", "action", "promise/loading", "pause/dismiss"],
    playgroundKey: null,
  },
  {
    slug: "attachment",
    name: "Attachment",
    tier: "molecule",
    source: "base-nova",
    status: "available",
    implementationChoice: "registry",
    configuration: ["file type", "progress", "failed", "removable", "compact"],
    playgroundKey: null,
  },
  {
    slug: "bubble",
    name: "Bubble",
    tier: "molecule",
    source: "base-nova",
    status: "available",
    implementationChoice: "registry",
    configuration: ["role", "alignment", "status", "actions", "long content"],
    playgroundKey: null,
  },
  {
    slug: "message",
    name: "Message",
    tier: "molecule",
    source: "base-nova",
    status: "available",
    implementationChoice: "registry",
    configuration: ["user/assistant/tool", "streaming", "error", "actions"],
    playgroundKey: null,
  },
  {
    slug: "calendar",
    name: "Calendar",
    tier: "organism",
    source: "base-nova",
    status: "available",
    implementationChoice: "registry",
    configuration: ["single/range/multiple", "disabled dates", "locale", "month/year"],
    playgroundKey: null,
  },
  {
    slug: "carousel",
    name: "Carousel",
    tier: "organism",
    source: "base-nova",
    status: "available",
    implementationChoice: "registry",
    configuration: ["orientation", "loop", "autoplay off/on", "controls", "slide count"],
    playgroundKey: null,
  },
  {
    slug: "chart",
    name: "Chart",
    tier: "organism",
    source: "base-nova",
    status: "native/third-party",
    implementationChoice: "existing",
    configuration: ["series", "chart type", "legend", "tooltip", "empty/loading/error"],
    playgroundKey: null,
  },
  {
    slug: "command",
    name: "Command",
    tier: "organism",
    source: "base-nova",
    status: "covered",
    implementationChoice: "registry",
    configuration: ["query", "groups", "empty/loading", "disabled", "shortcuts", "modal"],
    playgroundKey: "command-palette",
  },
  {
    slug: "form",
    name: "Form",
    tier: "organism",
    source: "base-nova",
    status: "native/third-party",
    implementationChoice: "native",
    configuration: ["valid/invalid", "submit pending", "server errors", "reset"],
    playgroundKey: null,
  },
  {
    slug: "menubar",
    name: "Menubar",
    tier: "organism",
    source: "base-nova",
    status: "available",
    implementationChoice: "registry",
    configuration: ["menus", "submenu", "checkbox/radio", "shortcuts", "disabled"],
    playgroundKey: null,
  },
  {
    slug: "navigation-menu",
    name: "Navigation Menu",
    tier: "organism",
    source: "base-nova",
    status: "native/third-party",
    implementationChoice: "native",
    configuration: ["active item", "viewport", "nested links", "mobile fallback"],
    playgroundKey: null,
  },
  {
    slug: "resizable",
    name: "Resizable",
    tier: "organism",
    source: "base-nova",
    status: "available",
    implementationChoice: "registry",
    configuration: ["orientation", "min/max", "collapse", "keyboard resize", "persistence"],
    playgroundKey: null,
  },
  {
    slug: "sidebar",
    name: "Sidebar",
    tier: "organism",
    source: "base-nova",
    status: "native/third-party",
    implementationChoice: "existing",
    configuration: ["collapsed/icon/mobile", "active item", "groups", "loading", "keyboard"],
    playgroundKey: null,
  },
  {
    slug: "message-scroller",
    name: "Message Scroller",
    tier: "organism",
    source: "base-nova",
    status: "available",
    implementationChoice: "registry",
    configuration: ["follow output", "paused", "jump-to-bottom", "streaming"],
    playgroundKey: null,
  },
];
